#Method-1 (Using List)
q = []
q.append(10)
q.append(20)
q.append(30)
print(q)
print(q.pop(0))
q.append(40)
print(q.pop(0))
print(len(q))
print(q[0])
print(q[-1],'\n')

#Method-1 (Using Deque)
from collections import deque
q = deque()
q.append(10)
q.append(20)
q.append(30)
print(q)
print(q.popleft())
q.append(40)
print(q.popleft())
print(len(q))
print(q[0])
print(q[-1])